name: synthiapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  advance_pdf_viewer: any
  circular_reveal_animation: ^2.0.0
  cloud_firestore: ^2.2.1
  cloud_functions: ^1.1.2
  cupertino_icons: ^1.0.2
  file_picker: ^4.2.0
  firebase_auth: ^1.3.0
  firebase_core: ^1.3.0
  firebase_storage: ^10.1.0
  flutter:
    sdk: flutter
  google_speech: ^2.0.1
  rxdart: ^0.27.2
  sound_stream: ^0.3.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  mailer: ^5.0.2
  open_file: ^3.2.1
  path_provider: ^2.0.2
  syncfusion_flutter_pdf: ^19.1.69-beta
  universal_html: ^2.0.8
  uuid: ^3.0.5
  webview_flutter: ^2.0.4
  syncfusion_flutter_calendar: ^19.3.55
  flutter_localizations:
    sdk: flutter
  syncfusion_localizations: ^19.3.56

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/logo.png
    - assets/avatar.png
    - assets/privacy_policy.html
    - assets/test_service_account.json
    - assets/blank_canva.png
