name: synthiaapp
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.7.4
  uuid: ^3.0.3
  shared_preferences: ^2.0.5
  ## Firebase packages
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  firebase_storage: ^8.0.1
  firebase_messaging: ^9.1.0
  cloud_firestore: ^1.0.3
  cloud_functions: ^1.0.2
  ## Text edition packages
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr/
      commit: 9b032d8
  ## Graphics packages
  google_fonts: ^2.0.0
  ff_navigation_bar: ^0.1.4
  lottie: ^1.0.1
  ## Notifications
  flutter_local_notifications: ^5.0.0
  ## Download
  path_provider: ^2.0.1
  permission_handler: ^6.1.1
  dio: ^4.0.0
  open_file: ^3.1.0
  ## Bluetooth packages
  flutter_ble_lib: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - secrets.json
    - assets/logo.png
    - assets/Logo_Synthia.png
    - assets/meeting.jpeg
    - assets/name.png
    - assets/phone.png
    - assets/company.png
    - assets/work.png
    - assets/profile.png