name: synthiaapp
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+15
  uuid: ^2.0.4
  shared_preferences: ^0.5.12+4
  ## Firebase packages
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.14
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.0
  ## Text edition packages
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr/
      commit: 9b032d8
  ## Graphics packages
  google_fonts: ^1.1.2
  ff_navigation_bar: ^0.1.4
  lottie: ^0.7.0+1
  ## Notifications
  flutter_local_notifications: ^4.0.1+1
  ## Download
  path_provider: ^1.6.27
  permission_handler: ^5.1.0+2
  dio: ^3.0.10
  open_file: ^3.0.3
  ## Bluetooth packages
  flutter_ble_lib: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - secrets.json
    - assets/logo.png
    - assets/Logo_Synthia.png
    - assets/meeting.jpeg
    - assets/name.png
    - assets/phone.png
    - assets/company.png
    - assets/work.png
    - assets/profile.png