name: synthiaapp
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  path_provider: ^1.6.5
  sliding_switch: ^0.0.3
  percent_indicator: ^2.1.7+3
  permission_handler: ^4.4.0+hotfix.2
  open_file: ^3.0.1
  flutter_local_notifications: ^1.3.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  provider: ^4.1.2
  uuid: ^2.0.4
  date_picker_timeline: ^1.2.1
  fitted_text_field_container: ^1.3.1+1
  flutter_email_sender: ^3.0.1
  cloud_functions: ^0.5.0
  intl: ^0.16.1
  firebase_messaging: ^5.0.2
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr/
      commit: 9b032d8
  quill_delta: 1.0.2
  cupertino_icons: ^0.1.3
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - secrets.json
    - assets/logo.png
    - assets/Logo_Synthia.jpg
    - assets/meeting.jpeg
    - assets/name.png
    - assets/phone.png
    - assets/company.png
    - assets/work.png
    - assets/profile.png